config/routes.rb
Rails.application.routes.draw do


  resources :members
  get 'home/index'

   root :to => "home#index"


  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "milia/registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
   
  belongs_to :user
  acts_as_tenant

  DEFAULT_ADMIN = {
    first_name: "Admin",
    last_name:  "Please edit me"
  }

  def self.create_new_member(user, params)
    # add any other initialization for a new member
    return user.create_member( params )
  end

  def self.create_org_admin(user)
    new_member = create_new_member(user, DEFAULT_ADMIN)
    unless new_member.errors.empty?
      raise ArgumentError, new_member.errors.full_messages.uniq.join(", ")
    end

    return new_member
      
  end

end

app/models/plan.rb
class Plan
  PLANS = [:free, :premium]

  def self.options
    PLANS.map { |plan| [plan.capitalize, plan]}
  end
end

app/models/tenant.rb
class Tenant < ApplicationRecord

   acts_as_universal_and_determines_tenant
  has_many :members, dependent: :destroy
  validates_uniqueness_of :name
  validates_presence_of :name
  
    def self.create_new_tenant(tenant_params, user_params, coupon_params)

      tenant = Tenant.new(tenant_params)

      if new_signups_not_permitted?(coupon_params)

        raise ::Milia::Control::MaxTenantExceeded, "Sorry, new accounts not permitted at this time"

      else
        tenant.save    # create the tenant
      end
      return tenant
    end

  # ------------------------------------------------------------------------
  # new_signups_not_permitted? -- returns true if no further signups allowed
  # args: params from user input; might contain a special 'coupon' code
  #       used to determine whether or not to allow another signup
  # ------------------------------------------------------------------------
  def self.new_signups_not_permitted?(params)
    return false
  end

  # ------------------------------------------------------------------------
  # tenant_signup -- setup a new tenant in the system
  # CALLBACK from devise RegistrationsController (milia override)
  # AFTER user creation and current_tenant established
  # args:
  #   user  -- new user  obj
  #   tenant -- new tenant obj
  #   other  -- any other parameter string from initial request
  # ------------------------------------------------------------------------
    def self.tenant_signup(user, tenant, other = nil)
      #  StartupJob.queue_startup( tenant, user, other )
      # any special seeding required for a new organizational tenant
      #
      Member.create_org_admin(user)
      #
    end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_universal_and_determines_account
  has_one :member, :dependent => :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_tenant!
  
     ##    milia defines a default max_tenants, invalid_tenant exception handling
     ##    but you can override these if you wish to handle directly
  rescue_from ::Milia::Control::MaxTenantExceeded, :with => :max_tenants
  rescue_from ::Milia::Control::InvalidTenantAccess, :with => :invalid_tenant

  before_action :authenticate_tenant!


end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Milia::ConfirmationsController

  def update
    if @confirmable.attempt_set_password(user_params)

      # this section is patterned off of devise 3.2.5 confirmations_controller#show

      self.resource = resource_class.confirm_by_token(params[:confirmation_token])
      yield resource if block_given?

      if resource.errors.empty?
        log_action( "invitee confirmed" )
        set_flash_message(:notice, :confirmed)
          # sign in automatically
        sign_in_tenanted_and_redirect(resource)

      else
        log_action( "invitee confirmation failed" )
        respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render :new }
      end

    else
      log_action( "invitee password set failed" )
      prep_do_show()  # prep for the form
      respond_with_navigational(resource.errors, :status => :unprocessable_entity){ render :show }
    end  # if..then..else passwords are valid
  end

  def show
   if @confirmable.new_record?  ||
      !::Milia.use_invite_member ||
      @confirmable.skip_confirm_change_password

     log_action( "devise pass-thru" )
     self.resource = resource_class.confirm_by_token(params[:confirmation_token])
     yield resource if block_given?
     if resource.errors.empty?
       set_flash_message(:notice, :confirmed) if is_flashing_format?
     end
     if @confirmable.skip_confirm_change_password
       sign_in_tenanted_and_redirect(resource)
     end
   else
     log_action( "password set form" )
     flash[:notice] = "Please choose a password and confirm it"
     prep_do_show()  # prep for the form
   end
   # else fall thru to show template which is form to set a password
   # upon SUBMIT, processing will continue from update
 end

  def after_confirmation_path_for(resource_name, resource)
    if user_signed_in?
      root_path
    else
      new_user_session_path
    end
  end

  private

  def set_confirmable
    @confirmable = User.find_or_initialize_with_error_by(:confirmation_token, params[:confirmation_token])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_tenant!, :only => [ :index ]

  def index
    if current_user
      if session[:tenant_id]
        Tenant.set_current_tenant session[:tenant_id]
      else
        Tenant.set_current_tenant current_user.tenants.first
      end
      @tenant = Tenant.current_tenant
      params[:tenant_id] = @tenant.id
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  # uncomment to ensure common layout for forms
  # layout  "sign", :only => [:new, :edit, :create]

  def new()
    @member = Member.new()
    @user   = User.new()
  end

  def create()
    @user   = User.new( user_params )

    # ok to create user, member
    if @user.save_and_invite_member() && @user.create_member( member_params )
      flash[:notice] = "New member added and invitation email sent to #{@user.email}."
      redirect_to root_path
    else
      flash[:error] = "errors occurred!"
      @member = Member.new( member_params ) # only used if need to revisit form
      render :new
    end

  end


  private

  def member_params()
    params.require(:member).permit(:first_name, :last_name)
  end

  def user_params()
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/home/index.html.erb
<% if current_user %>
<h3>Organization:
    <%= @tenant.name %></h3>
<% else %>
<div class="jumbotron">
    <h2>Welcome to the Project Management Application!</h2>
    <p class="lead">
        You'll love managing your project with our SaaS application. Please take a look at our great plans
    </p>
</div>
<div class="row">
    <div class="plans clearfix">
        <div class="col-6 plan">
            <h2>Free Plan</h2>
            <div class="price pull-right">
                Price: Free
            </div>
            <div class="features">
                <ul>
                    <li>Unlimited file uploads</li>
                    <li>Responsive design</li>
                    <li>Access anywhere</li>
                    <li>1 project</li>
                </ul>
            </div>
            <p>
                <%= link_to 'Sign Up', new_user_registration_path(plan: 'free'), class: 'btn btn-primary sign-up' %>
            </p>
        </div>
        <div class="col-6 plan">
            <h2>Premium Plan</h2>
            <div class="price pull-right">
                Price: $10
            </div>
            <div class="features">
                <ul>
                    <li>Unlimited file uploads</li>
                    <li>Responsive design</li>
                    <li>Access anywhere</li>
                    <li class='extra'>Unlimited projects</li>
                </ul>
            </div>
            <p>
                <%= link_to 'Sign Up', new_user_registration_path(plan: 'premium'), class: 'btn btn-primary sign-up' %>
            </p>
        </div>
    </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="nav-dark"> 
      <header> 
        <h2><a href="/">SaaS Rails</a></h2>
      </header>
      <ul class="menu-items"> 
        <% if current_user %>
        <li class="f-col-1 flex-center user-name">
          <%= link_to "<i class='fa fa-users'></i> Add Members".html_safe,new_member_path,class: 'navbar-link btn btn-primary' %>
        </li>
          <li class="f-col-1 flex-center user-name">
          <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
          </li>
          <li class="f-col-1 flex-center logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
          <% else %>
          <li class="f-col-1 flex-center pull-right">
          <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
          </li>
          <% end %>
      </ul>
      <ul class="mobile-nav flex-center"> 
        <div class="hamburger"></div> 
      </ul>
      <div class="flyout">
        <div class="bar"> 
          <header class="text-light f-col-4"> 
            <img src="img/logo-thick-light.svg" alt="Tuxedo Logo"> 
          </header> 
          <div class="close f-col-1"></div> 
        </div>
        <ul class="flyout-menu"> 
          <% if current_user %>
          <li>
            <%= link_to "<i class='fa fa-users'></i> Add Members".html_safe,new_member_path,class: 'navbar-link btn btn-primary' %>
          </li>
            <li class="user-name">
            <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
            </li>
            <li class="logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% else %>
            <li class="pull-right">
            <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
            </li>
            <% end %>
        </ul>
      </div>
    </nav>
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
    <h1><%=t '.title', :default => [:'helpers.titles.new', 'Invite New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= form_for(@member, :html => { :class => "form login" }) do |f| %>
<% if @member.errors.any? %>
<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@member.errors.count, "error") %>
            prohibited this Member from being saved:</h3>
    </div>
    <div class="panel-body">
        <ul>
            <% @member.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>
<% if @user.errors.any? %>
<div id="error_expl" class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %>
            prohibited this Member from being saved:</h3>
    </div>
    <div class="panel-body">
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>
<%= fields_for( :user ) do |w| %>
<div class="control-group">
    <%= w.label :email, :class => "control-label" %>
    <div class="controls">
        <%= w.text_field :email, :class => 'form-control' %>
    </div>
</div>
<% end %>
<div class="control-group">
    <%= f.label :first_name, :class => "control-label" %>
    <%= f.text_field :first_name, :class => "form-control" %>
</div>
<div class="control-group">
    <%= f.label :last_name, :class => "control-label" %>
    <%= f.text_field :last_name, :class => "form-control" %>
</div>
<br/>
<div class="control-group">
    <button class="btn btn-primary" type="submit">
        Create user and invite
    </button>
</div>
<% end %>